version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "82:8081"
    environment:
      - REDIS_HOSTS=redis:redis:6379
    depends_on:
      - redis
networks:
  localnet:
    driver: bridge
